identifier: l2mdofuc86t9w5l2
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: client
homeFolder: D:\Projects\KaarKg - Ecommerce\client
distFolder: dist/static
outDir: D:\Projects\KaarKg - Ecommerce\client\dist\static
handle404: ''
allowErrorCollect: false
